# Site
repository: donore97/oreoluwaadesina
# favicon: images/favicon.ico

# Personal info
name: Oreoluwa Adesina
title: Electrical Engineer
email: oreoluwaadesina40@gmail.com  
website: https://donore97.github.io/oreoluwa-adesina-resume/

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Oreoluwa and I'm a Computer and Electrical Engineer. gaining teamwork and leadership skills. In addition to this, I also have some experience analyzing data and interpreting the data in a form that can be understood and used to solve problems.

   Skills:
  <mark>Development</mark>: Data Analytics, PYTHON, JAVA, MATLAB, C, Docker, Git, Image Processing, VLSI.
  <mark>Comunication</mark>: Created Initiatives for technical and executive professionals.
  <mark>Leadersip</mark> Founder: AnonPi and OreoluwaAdesinaPhotography.
  <mark>Holistic View</mark>: Strong Understanding of Hardware concepts and Industry knowledge.
  <mark>Business</mark>: Strategy and Planning, Pitching, Business Analysis.
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Photography
   - Music
   - Consulting
#-  [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
